// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import java.awt.Color;

import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;

/************************************************************/
/**
 * 
 */
public class BotFactory {
	public static Robot getRobotType(String type){
		if(type.equalsIgnoreCase("mapper")){
			return new Mapper(new Vector3d(-9,0,9), "mapper", new Color3f(Color.blue));
		} else if(type.equalsIgnoreCase("rescuer")){
			return new Rescuer(new Vector3d(-9,0,8), "rescuer", new Color3f(Color.yellow));
		}
		return null;
	}
}

