// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import java.util.ArrayList;
import simbad.sim.Agent;
import javax.vecmath.Point3d;
import javax.vecmath.Vector3d;
import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public class CentralStation extends Agent {
	
	//create one instance of this class SINGLETON
	private static CentralStation cs = new CentralStation(new Vector3d(15,0,15), "CentralStation");
	private ArrayList<Point3d> posArray; 
	Robot mapBots[];
	Robot resBots[];
	
	//private constructor
//		TODO do we need more stuff in the constructor? 
	private CentralStation(Vector3d position, String name){
		 super(position, name);
		 posArray = new ArrayList<Point3d>();
		 mapBots = new Mapper[2];
		 resBots = new Rescuer[2];
	};
	
	//returns the lonely instance SINGLETON
	public static CentralStation getInstance(){
		return cs;
	}	

	public void setCoordinates(Point3d position) {

    	boolean contains = false;
    	// check if position are already present in list
    	for(int i=0;i<posArray.size();i++){
    		if((position.x == posArray.get(i).x) && (position.z == posArray.get(i).z)){
    			contains = true;
    		}
    	} // otherwise add new node
    	if(!contains){
    		posArray.add(position);
        	System.out.println("new target coordinates added");
        	System.out.println("curretn size of array is: " + posArray.size());
    	} else {
    		System.out.println("already existing target coordinates");
    	}
	}

	public void sendMapper(EnvironmentDescription env, int howmany) {
		
		for(int i=0; i<howmany; i++){
			
			mapBots[i] = DeviceFactory.getRobot("mapper");
			mapBots[i].myTurn = true;
			env.add(mapBots[i]);
			
		}
	}
	
	public void sendRescuer(EnvironmentDescription environment, int howmany) {
		
		for(int i=0; i<howmany; i++){
			
			resBots[i] = DeviceFactory.getRobot("rescuer");
			environment.add(resBots[i]);
		}
	}
	
	public void initBehavior(){
		this.detach();
		System.out.println("I exist and my name is "+this.name);
	}
	
	public void performBehavior(){
		
		if (getCounter() % 5 == 0){

			if(mapBots[0].itExists() && mapBots[1].itExists()){
				if(posArray.size() >=4 ){
						mapBots[0].myTurn = false;
						mapBots[1].myTurn = false;
						mapBots[0].setMode("done");
						mapBots[1].setMode("done");
						mapBots[0].detach();
						mapBots[1].detach();
//						calculateMap();
				} else {
						if (mapBots[0].getMode()=="severeFault"){
							mapBots[0].detach();
						} else if (mapBots[1].getMode()=="severeFault"){
							mapBots[1].detach();
						}
				}
			}
			for(int i=0; i<2 ;i++){
				if(!resBots[i].itExists() && mapBots[i].getMode()=="done"){	
					resBots[i].attach();
					resBots[i].myTurn = true;
					resBots[i].setLocations(posArray);
				}
			}
		}
	}

};