// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import javax.vecmath.Color3f;
import javax.vecmath.Point3d;

import java.util.ArrayList;
import javax.vecmath.Vector3d;

import RootElement.Robot;
import simbad.sim.RobotFactory;

/************************************************************/
/**
 * 
 */
public class Rescuer extends Robot {
	
	private ArrayList<Point3d> victimPos = new ArrayList<Point3d>();
	private Point3d myPos;
	
	//constructor
	public Rescuer(Vector3d position, String name, Color3f color) {
		super(position, name);
		this.setColor(color);
		this.setMode("reach");
        this.bumpers = RobotFactory.addBumperBeltSensor(this, 16);
        this.sonars = RobotFactory.addSonarBeltSensor(this, 8);
        this.lamp = RobotFactory.addLamp(this);
    	
	}
	
	public void setLocations(ArrayList<Point3d> copy){
		
		victimPos = (ArrayList<Point3d>)copy.clone();
		System.out.println(victimPos.toString());
	}

	@Override
	public void initBehavior() {
		System.out.println("I exist but is not my turn [" + this.name + "]");
		this.detach();
	}

	public void goAround(){
		this.getCoords(myPos);

	}

	@Override
	public void performBehavior() { 
		if (this.itExists() && this.myTurn){
			if(this.getCounter() % 5 == 0) {
				setTranslationalVelocity(0.5);
				
				obstacleDetected();
								
				if(this.getMode()=="rescue"){
					if ((this.getCounter() % 50) == 0) {
						if(myPos.x > victimPos.get(0).x){
							if(myPos.y > victimPos.get(0).y){
								rotateY(-Math.PI/4);
							} else if(myPos.y < victimPos.get(0).y){
								rotateY(-Math.PI*3/4);
							} else {
								rotateY(-Math.PI/2);
							}
						} else if(myPos.x < victimPos.get(0).x) {
							if(myPos.y > victimPos.get(0).y){
								rotateY(Math.PI/4);
							} else if(myPos.y < victimPos.get(0).y){
								rotateY(Math.PI*3/4);
							} else {
								rotateY(Math.PI/2);
							}
						}
					
					}
				} else if (this.getMode()=="avoid"){
					goAround();
				}

//				if(bumpers.oneHasHit()){
//					rotateY(-15);
//				} 
			}
		}
	}

};
