// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;

import RootElement.Environment;
import RootElement.Robot;
import simbad.sim.RobotFactory;

/************************************************************/
/**
 * 
 */
public class Rescuer extends Robot {
	
	//constructor
	public Rescuer(Vector3d position, String name, Color3f color) {
		super(position, name);
		this.setColor(color);
        bumpers = RobotFactory.addBumperBeltSensor(this, 16);
        sonars = RobotFactory.addSonarBeltSensor(this, 8);
    	
	}

	@Override
	public void initBehavior() {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void performBehavior() {
        
		// perform the following actions every 5 virtual seconds
			
			//setTranslationalVelocity(0.5); 
		if (this.myTurn){
			if(getCounter() % 5 == 0) {
				
				setTranslationalVelocity(0.5);
//				translateTo(new Vector3d(1,0,1));
				

				if(bumpers.oneHasHit()){
					rotateY(-45);
				} 
			}
		}
	}

	@Override
	public boolean missionComplete() {
		// TODO Auto-generated method stub
		return false;
	}
};
