// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;

import RootElement.Robot;
import simbad.sim.RobotFactory;

/************************************************************/
/**
 * 
 */
public class Rescuer extends Robot {
	
	//constructor
	public Rescuer(Vector3d position, String name, Color3f color) {
		super(position, name);
		this.setColor(color);
		this.setMode("reach");
        this.bumpers = RobotFactory.addBumperBeltSensor(this, 16);
        this.sonars = RobotFactory.addSonarBeltSensor(this, 8);
        this.lamp = RobotFactory.addLamp(this);
    	
	}

	@Override
	public void initBehavior() {
		System.out.println("I exist but is not my turn [" + this.name + "]");
		this.detach();
	}


	@Override
	public void performBehavior() { 
		if (this.itExists() && this.myTurn){
			if(this.getCounter() % 10 == 0) {
				setTranslationalVelocity(0.5);
				if ((this.getCounter() % 50) == 0) {
					this.setRotationalVelocity(Math.PI / 2 * (0.5 - Math.random()));
				}

				if(bumpers.oneHasHit()){
					rotateY(-5);
				} 
			}
		}
	}

};
